<template>
<title>A Stormregion-sztori - S.W.I.N.E. Mods and more</title>
<div class="main">
<p>A Stormregion-sztori (Forrás:<a href="http://csakegypohar.blogspot.hu/2009/03/pc-guru-kapter-van.html#comment-form">http://csakegypohar.blogspot.hu/2009/03/pc-guru-kapter-van.html#comment-form</a>)</p>
<p>S.W.I.N.E., Panzers, Phase one és Phase two – ki ne emlékezne ezekre a kultikus nevekre, amelyeket annak idején a magyar játékpiac legmeghatározóbb címei közé sorolhattunk. talán nem is volt akkoriban olyan második világháborús játék, amely kis hazánkban és világszerte egyaránt oly sikert aratott volna, mint a Panzers.</p>
<p>Állj! Mi ? Phase Two ? Miféle kultikus név ? A játék csőd volt, amíg nem felezték a vételárát. Felezés után tudott csak tarolni és a top10-be kerülni spanyolban és olaszban, 2005 karácsonyán. (Július 25-én jelent meg (Hazánkban augusztus 15-én), novemberben már közel fél áron lehetett kapni. Ráadásul a fórumos szereplése is közel nulla, minden külföldi és magyar fórumon max 10 emberke beszélgetett olykor erről a kultikus (kac-kac) izéről.)
Ha emlékezetem nem csal, épp egy pcguru-s csinált a PP2-nek egy fanoldalt (az a személy, aki szerkesztette a nyomtatott lapban is a pp-fan részt), amivel aztán érdektelenség miatt felhagyott (a szerkesztő írta, hogy ez okból kifolyólag lép olajra).</p>
<p>Egy magyar cég tündöklése és bukása</p>
<p>A Stormregion sikercsillaga szinte ott ragyogott a csúcson, miért történhetett mégis, hogy ez a rendkívül ígéretes magyar játékfejlesztő cég végül oly szomorú véget ért? Hiszen míg pont egy évvel ezelőtt még a Cold War leendő sikeréről készítettünk velük interjút, addig mostanra a cég tönkrement, tagjai szétszéledtek, tervezési fázisban lévő projektjeiket leállították. Interjúkon, beszélgetéseken keresztül jártunk utána, vajon mitől válhatott oly sikeressé ez a kis magyar cég, illetve milyen okok vezettek mégis a közelmúlt bukásához…</p>
<p>Fogadni mernék rá, hogy nem írjátok le... és hazudni fogtok.</p>
<p>Disznók és nyulak?
Ti most vicceltek, ugye?</p>
<p>Bár szerintem sokan a legmeghatározóbb címként a Stormregionnál mindig is a Panzerst emlegettük, mégsem ez volt az „első fecske”, hanem a S.W.I.N.E., amely disznók és nyulak harcáról szólt. A humoros stratégiai játék ugyan alapelemeiben nem rázta meg az RTSek világát, de a kacagtató játékötlet miatt mégis sokan megszerették. Érdekesség, hogy a S.W.I.N.E. tulajdonképpen nem is „tősgyökeres” Stormregion játék, ugyanis még a Channel 42 nevű cég kezdte el fejleszteni.</p>
<p>Azt se tudtuk, hogy létezik olyan cég, hogy Channel42, mikor elkezdtük fejleszteni a SWINE-t (Trail), a fejlesztés kezdete után 3 (azaz három) évvel találkoztunk velük először.</p>
<p>A tulajdonosok azonban ugyanazok voltak, akik a Stormot 2001-ben megalapították (a hazugság bűn ! - Mr. Water) , úgyhogy olyan hatalmas változásról azért nem beszélhetünk. (köhöm-köhöm - Mr. Water) A játék alapötlete az egyik fejlesztő, Bánky-Horváth Attila agyából pattant ki, aki nagy rajongója volt Orwell Állatfarm című regényének. (Az első igazságmorzsa. - Mr. Water)
A S.W.I.N.E. tényleg szórakoztatóra sikeredett, a stormosok azonban éreztették, hogy annyira nem volt átütő siker, mint ahogy azt most utólag gondolnánk. (Mégis többszázan játszanak vele gamespy-on 7 évvel a megjelenés után. Tavaly nyáron én is fenn voltam. - Mr. Water) A fejlesztők nem is erre bazíroztak: szerintük a S.W.I.N.E. szerepe leginkább az volt, hogy a Stormregion számára megnyissa a korábban zárt kapukat a kiadók felé. (Köhöm-köhöm. - Mr Water) A S.W.I.N.E. mindvégig rétegjáték maradt – két okból is. Egyrészt a mi közép-kelet európai humorunk nyugaton annyira nem emészthető, másrészt nagyjából ekkoriban ment tönkre az eredeti kiadó, a Fishtank. Bár a játék ugyan megjelent a Fishtank égisze alatt, de a széthullás alatt álló cég már nem tudott a marketingre figyelni. Meglepő módon Franciaországban viszont sikeres volt a játék, a csigazabálók ugyanis – a németekkel ellentétben
– értékelték a S.W.I.N.E. humorát… (Forrás ? - Mr. Water) Talán ebben az is szerepet játszott, hogy a ravasz nyuszikkal szívesen azonosultak a francia játékosok, míg a németek annyira már nem rajongtak a disznókkal való „hasonlatossághoz” pedig a sztori kicsit ezt sugallta. (Szeretnéd ? - Mr. Water) Mindenesetre a legfontosabb ténynek azt tekintette a cég, hogy elkészült egy igen jól kidolgozott, befejezett termék, amellyel a kiadók előtt már lehetett „villogni”.</p>
<p>Panzers Über Alles</p>
<p>Ha elmondhatjuk, hogy a S.W.I.N.E. inkább a franciák szívét nyerte meg (Már kérdeztem: forrás ? - Mr. Water), akkor azt is gyorsan hozzá kell tennünk, hogy a II. világháborús téma viszont a németek fantáziáját indította be, hiszen ebben az országban mindig is nagy múltja volt a nagy világégést feldolgozó stratégiai játékoknak. A Stormregion ebben az időszakban két játékot fejlesztett azon az alapon, hogy amelyiket hamarabb el tudják adni egy kiadónak, azt fejezik be. A nyerő kártya a Panzers volt – méghozzá a CDV kiadó kezében. A másik játék egyébként a római korszakot dolgozta volna fel Gladius címmel (Rome: Total War stílusban), de mivel a másik projekt előbb elkelt, így nem folytatták a fejlesztését. Bizonyos vélemények szerint a Panzers sikerét – amellett, hogy tényleg jól sikerült és élvezetes játék – sokban köszönheti annak, hogy a CDV „dupla vagy semmi” alapon iszonyatos pénzeket ölt belé, a német cég ugyanis akkoriban anyagi nehézségekkel küzdött és úgy döntött, mindent belead ebbe a játékba (főleg marketing, például tévéreklámok téren), csak hozza be a megfelelő bevételt…</p>
<p>Ugye mi rossz barátok vagyunk?</p>
<p>Be is hozta. A gond csak az volt, hogy a Stormregion akkori tulajdonosai között komoly ellentétek alakultak ki. Egyik részük úgy gondolta, hogy a Stormregionnak kisebb, jól működő baráti társaságként kellene továbbra is működnie és úgy koncentrálnia a további projektekre, a többiek – akik inkább üzleti megközelítéssel álltak a kérdéshez – viszont úgy képzelték el, hogy egy erős, nagy, profi céget kell építeni komoly csapattal, sokféle, egyszerre futó fejlesztéssel és aztán eladni az egészet.</p>
<p>Na ne ! Mint írtam már, hazudni bűn. (Nem én találtam ki.)
Semmi de semmi ilyesmiről nem volt szó. Tudomásom szerint arról volt szó, hogy a cég feje átvágta a Stormregion tényleges vezetését, azokat, akik a cégvezetővel és projektmenedzserrel szemben a fejlesztés alatt rendesen bejártak dolgozni, vezették a céget és menedzselték a projektet azok helyett, akik ilyen néven futottak a cégnél. Átvágta és becsapta őket, évről-évre soványodott, sorvadt az ígérethalmaz. 2002-ben én is fültanúja voltam egy ígéretömlengésnek, amit a cégvezető rendezett, nekem irreális volt, hazugságnak gondoltam, és akkor sejtettem, hogy vége lesz hamarosan a történetnek. 2004 tavaszán vége is lett, új történet kezdődött, a szakmai, gazdasági csőd története.</p>
<p>Az ellentétek túlságosan is felerősödtek. Emiatt az a szerencsétlen helyzet állt elő, hogy a tulajdonosok egy része (Pontosabban a 6 tulajdonosból 5 - Mr. Water), illetve a csapat 80%-a fogta magát, otthagyta a Stormregiont és elment a Mythis-be. A Myhtis berkein belül pedig az ottani csapat nekiállt a Joint Task Force fejlesztésének, amely feltűnően hasonlított a Panzers motorjára...
Nagyon úgy nézett ki tehát, hogy az ex-stormos Mythis tagok „magukkal vitték” a Panzers technológiáját (fejlesztési kitek, toolok stb.) (Én inkább úgy fogalmaznék, hogy maguk mögött felejtették. Ugyanis az az ő érdemük volt(!), ha azt tették volna, mint a felperes, sz@rtak volna bele az egészbe, akkor a cég 2003-ban bezár. Egy hibát vétettek, hogy amikor válásra került a sor, nem rendezték a jogi dolgokat, pedig joguk lett volna hozzá, tanúk lettek volna, én is - Mr Water), vagy inkább kevésbé elegáns kifejezéssel élve „lenyúlták” lta(Hogy ki nyúlta le, azt az Idő megmutatta, bebizonyította. A Stormregion van, a &quot;Stormregion&quot; több évnyi vajúdás után megszűnt. Nem csak hogy nem tudtak elszakadni az áluk sokra tartott, de ismeretlen Gepard engine-től, de nem tudtak hozzászólni az engine-hez, lásd pl. CPCW swine-os útkeresője - Mr. Water), és ebből készült a JTF. Ráadásul a terméket több helyen is úgy reklámozták, hogy a Panzers fejlesztőinek új játéka. (És ezzel mi a baj ? Van olyan sérült, torz énképű gerinctelen alak, akit az igazság zavar ? - Mr. Water)
Ez természetesen igencsak frusztrálta a Storm vezetőségét, ezért úgy döntöttek, hogy jogi útra terelik az ügyet. (Már az ügy előtt ráküldték a BSA-t a Mithisre... - Mr. Water) A vádak be is bizonyosodtak, sőt, a szóbeszéd szerint annak a szoftvernek a forráskódjában, amelyet a rendőrség lefoglalt, olyan leírások is szerepeltek, hogy „Copyright by Stormregion”. (Az már akkor benne volt tudtommal, mikor még nem is ismertük a felperest. - Mr. Water) Elkezdtek folyni a tárgyalások a JTF-et kiadó HD Interactive-val, hogy valahogy próbálják rendezni az ügyet. Bár a Stormregion azt is megtehette volna, hogy leállíttatja a JTF fejlesztését, végülis arra a megegyezésre jutottak, hogy némi licencdíj fejében a Mithis befejezheti a játékot.</p>
<p>A második fázis</p>
<p>No de térjünk vissza a Stormregion saját történetére, amely annál is izgalmasabb, mert a cég hirtelen igencsak furcsa helyzetben találta magát. (Nem volt semmi furcsa abban, hogy évekig nem csináltak semmit, csak újra meg újra a mi játékunkat adták ki és a piac erre nem volt vevő - Mr. Water) A Panzers Phase 1 (tehát maga az első Panzers) hatalmas siker volt, a kiadó alig várta a folytatást, amelyre meg is volt a szerződés. Egyetlenegy dolog hibádzott: az emberanyag, ismét szerencséje volt. Egyrészt maradtak tehetséges időszakban vált zűrössé a másik magyar játékfejlesztő cég, a Digital Reality helyzete is, ahonnan sokan átjöttek, Persze az igazi vonzerőt a meglévő szerződés jelentette. így nem volt gond a határidők betartásával. Igy készülgetett a CDV kiadó hosszabbította meg, ennek köszönhetően egy új kampányt is beleraktak a játékba a stormosok. (Ha kérhetem, amikor a 2004 május utáni időszakról írsz, akkor a &quot;storm&quot;ot tedd idézőjelbe. - Mr. Water)
A fejlesztők különösen büszkék arra, hogy a vadonatúj emberekből összeverbuválódott csapat is egy olyan játékot adott ki a kezei közül, amely nemzetközi szinten ugyanolyan eredményeket, kritikákat ért el, mint az eredeti Panzers. A Stormregion lendülete tehát nem tört meg…</p>
<p>Sokan vagyunk és elegen</p>
<p>A Storm végül nem kevesebb, mint 120 főre duzzadt és gőzerővel folyt a Rush for Berlin fejlesztése. Az eredeti koncepció szerint az egyetlen „nyersanyag” a játékban az idő volt, tehát ezzel kellett megküzdenie a játékosnak (a legvégén ez az ötlet némileg átalakult). A készítők igyekeztek eltávolodni a Panzers-világtól, de ez leginkább a dizájnban jelentkezett, amely sokkal színesebb, élénkebb látványt nyújtott, mint elődei. (Színesebb ? Élénkebb ? Igen, így is lehet fogalmazni. - Mr. Water) A Rush for Berlin végül közepes sikereket ért el. (Közepes ? A fejlesztők nem ezt mondták, hanem azt, amikor a szupportról volt szó, hogy:&quot;Minek, úgyse játszik vele senki.&quot;)
Forrás:</p>
<img src="~/assets/content/storm/support.jpg"/>
<p>Mindig is az motoszkált a fejemben, hogy a magyar játékokra mennyire jellemző ez a rendkívül erős kötődés a második világháborús stratégiákhoz, így felmerült bennem, hogy nem volt-e már akkor is kifulladóban a téma. Ezen vonal mentén kérdeztem a korábbi fejlesztőket, hogy nem gondoltak-e rá már akkoriban, hogy esetleg műfajt kellene váltani. Szerintük az újságírók egyre jobban unták már a témát és ennek hangot is adtak a sajtóban világszerte.
Mindennek ellenére ezek a játékok eladhatóak voltak, tehát közönségsikert értek el és nyereséget hoztak. Másrészt mind a kiadók, mind a játékosok már tapasztalták, hogy a Stormregion ebben profi, és azt várták, a suszter maradjon a kaptafánál.</p>
<p>Nem várta senki, ez kizárólag az ő döntésük volt. Ők csapták be a kiadókat a Panzers Phase One eladásaira hivatkozva. Ugye nem gondolod, hogy a 10tacle és az EA kereste meg őket, hogy:&quot;Figyeljetek má, kéne nekünk egy hidegháborús sz@r rts, retro legyen, 4-5 évvel legyen elmaradva grafikailag, szeretnénk már csődbe menni.&quot;, he ?</p>
<p>Konzolvilág és hidegháború</p>
<p>A változás szele végül megcsapta a stúdiót is, és ezt mi sem mutatja jobban, mint Panzers: Cold War, amely ugyan sok tekintetben emlékeztetett az elődökre, de mégsem a második világháborút dolgozta fel, hanem a közvetlenül utána tartó hidegháborús időszakot.
A fejlesztők tényleg igyekeztek modernebb hadviselést és modernebb egységeket rakni a játékba (még olyanokat is, amelyek akkor még csak prototípusként léteztek), de őszintén szólva amikor egy évvel ezelőtt megláttam a Cold Wart – azon kívül, hogy a játék a Gepard motornak köszönhetően döbbenetesen szép volt – túlzott különbséget nem észleltem a korábbi részekhez képest.</p>
<p>Azért nem észleltél, mert nem volt mit. Látod ? Ezzel is engem igazolsz, és magadat hazudtolod meg. Képzeld, más sem észlelt semmit, ezért fulladt be a pcgurus panzersfan oldal.</p>
<p>»Miközben a felvásárlás másoknak biztonságot hozott, addig a Stormregionnak csak a vesztét...«
Ha a 10Tacle nem vásárolja fel, akkor már 2007 nyarán csődbe ment volna a cég, így nyertek több, mint fél évet. A &quot;Stormregion&quot; KFT vezetősége 2007 tavaszán kilincselte végig a szakmát, de nagy ívben és magasról... hát elkerülték őket. Volt olyan alkalmazott aki a blogján számolt be a történésekről, volt aki a pc-s játékpiacot hibáztatta. Egyik alkalmazottjuk pedig imigyen fakadt ki:&quot;a kovetkezo varazsszavakon gondolkozz el: Haldoklo PC-s piac, Konzolra atallas, Országos gazdasági &quot;mélypont&quot;, mely egy befektetőnek nem túl vonzó ...)&quot;
Nem, nem a gazdasági mélypont nem volt vonzó a befektetőnek, hanem a &quot;Stormregion&quot; KFT senkinek. Nem véletlen, hogy a CP:CW kiadója vásárolta fel a céget, ahogy az sem véletlen, hogy a tőzsdén a felvásárlás után kezdett el zuhanni a 10tacle részvényeinek árfolyama olyan mértékben, ahogy előtte nem volt rá példa...</p>
<p>A Cold War mellett ugyanakkor két másik játékprojekt is készülgetett. Az egyik egy Xbox 360-ra és PS3-ra készült külső nézetes akció-szerepjáték volt, a 7th Age, amely Unreal motort használt volna és a háttérvilágot a M.A.G.U.S. magyar szerepjáték szolgáltatta volna. Nagyobb kaliberű magyar konzoljáték mindez idáig ritkán készült, ami nem véletlen, hiszen sokkal komplexebb és költségesebb egy ilyen fejlesztés, nehezebb szerződést szerezni és drága a Microsoft, illetve a Sony fejlesztői kit. Sajnos a Stormregion előbb bukott meg, minthogy ez a játék elkészülhetett volna. A másik project egy Sony PSPre készült körökre osztott, óriási lépegető robotos játék, a Mythran Wars volt, amely viszont a Deep Silver kiadásában fog hamarosan napvilágot látni. (Hamarosan ? - Mr. Water) A Mythran Wars érdekessége, hogy az átvezető animációkat „Geek”, egy magyar képregénygrafikus, magyar modell lányok közreműködésével készítette. „Geek” azóta a Cryteknél dolgozik designerként: ő tehát egyike azon keveseknek, akiknek sikerült megtalálni a helyüket más játékcégeknél, viszont a Stormregion többi munkatársára sajnos ez nem volt jellemző… (Milyen szerencse ez a szakmának - Mr. Water)</p>
<p>Új tulajdonos a láthatáron</p>
<p>Még a bukás előtt, a Panzer sikereit követően kezdett érdeklődni a Storm iránt a 10tacle nevű német cég (Ezt mondta Weibel, csak akkor azt nem értem, hogy miért kilincselték a szakmát 2007 tavaszán... - Dr. Water), méghozzá igen konkrét célokkal: fel akarták vásárolni a magyar fejlesztőcéget. Megkezdődtek a tárgyalások és a tranzakció meg is történt. A magyar cég vezetősége egyértelmű sikernek könyvelte el az üzletet és a munkatársak is úgy érezték: így
legalább hosszabb távra biztosítva lesz a cég jövője.
A 10tacle égisze alatt aztán gőzerővel folytatódtak a különböző projektek. A 7th Age-nek elkészültek a concept artjai, és szépen haladt a Cold War is. A 10tacle üzleti modellje azonban igen sajátos volt. Nem saját tőkéből, hanem pénzügyi befektetőktől gyűjtötte be a játékok finanszírozására szánt pénzt. (A részvénytársaságnak, igen, eltaláltad, pont ez a lényege. - Mr. Water) Csak ha már elkészült az adott játék, akkor ment oda a nagyobb kiadókhoz, hogy eladja nekik a terméket. Természetesen ezen neki is szép haszonkulcsa volt, még azután is, hogy a befektetőknek visszafizette a pénzüket.
A Panzers: Cold War esetében az Electronic Arts lett volna a szóban forgó nagy kiadó (tudtommal ő csak az európai kiadásért felelt volna - Mr. Water), és igen előrehaladottak voltak már a tárgyalások. A lipcsei Games Conventionön még be is mutatták az EA standján az
akkori verziót. Még az is szóba került, hogy a 7th Age-et is az EA dobja majd piacra. Sajnos azonban az események egy egészen más fordulatot vettek…</p>
<p>A „polip” süllyedni kezd…</p>
<p>A 10tacle ugyanis hamarosan komoly pénzügyi bajba került és ennek meg is mutatkoztak a jelei: részvényei ingadozni kezdtek, és több szerződéses partnerük késve, vagy egyáltalán nem kapta meg a járandóságát. Ezen jelek azonban csak „baljós árnyak” voltak, a Stormregion munkatársai ugyanis továbbra is megkapták a fizetésüket – legalábbis egy ideig. Először a 2008. februári fizetés csúszott két hetet, azonban azt még átutalták a magyar fejlesztőknek, akik kissé már kezdtek ugyan aggódni – hiszen ilyen még nem fordult elő – de azért még bizakodtak… Nem sokkal ezután, a 10tacle kétfős delegációja megérkezett a Stormregion főhadiszállására és elmagyarázták, hogy a 10tacle üzleti koncepciója egy német törvényen alapult, amely kedvezett az ilyen típusú befektetéseknek. (Hasonló módon finanszírozta Uwe Boll is éveken keresztül
bűn rossz filmjeit.) A gond csak az, hogy a törvény megváltozott, így már sokkal nehezebben tudnak majd új befektetőket találni. Ráadásul egyre komolyabbá váltak a pénzügyi problémák is. Ennek ellenére így búcsúztak a találkozó végén: „ne parázzatok srácok, ezek a problémák megoldódnak!”.</p>
<p>Szomorú április (Már akinek. - Mr. Water)</p>
<p>A biztatás ellenére a „problémák” olyannyira „nem oldódtak meg”, hogy végül áprilisban a 10tacle nem küldött több fizetést. (Bölcs döntés volt. - Mr. Water) Az emberek először csak vártak és vártak, aztán a türelmetlenebb fejlesztők gyorsan leléptek, hogy másik állás után nézzenek. Akik maradtak, azok be-bejártak dolgozni (Mit csinálni ? - Mr. Water) egy ideig, de igazából senki sem tudta, hogy mi a valós helyzet. Végül nyáron történt meg a „game over”: bezárták az irodát, már dolgozni sem lehetett bejárni és ezzel rengetegen kerültek az utcára. Megoldás lehetett volna, és a még meglévő alkalmazottak között sokan bíztak abban, hogy esetleg a 10tacle eladja a Stormregiont egy másik cégnek. Érdekes módon, amikor valaki megkereste őket ezzel kapcsolatban, a 10tacle vezetőségének mindössze ennyi volt a válasza a vásárlási ajánlatra: „Stormregion is not for sale.” Hogy vajon miért ragaszkodtak ahhoz, hogy a süllyedő hajóval magukkal rántsák a Stormregiont, azt már valószínűleg sohasem tudjuk meg (Van egy sejtésem. Én legalábbis azt tenném a helyükben. - Mr. Water), de ezzel a lépéssel a túlélés utolsó esélyét is elvették a srácoktól…(A srácok is elvették a túlélés esélyét a 10tacle-tól, hogy ilyen köhöm-köhöm &quot;játékot&quot; kókányoltak milestonecsúszással. - Mr. Water)</p>
<p>Epilógus</p>
<p>A szomorú történet végül a Panzers: Cold War sorsát illetően happy enddel zárul. A régebbi projektvezetőt 2008 nyarán megkereste az a befektető cég, amelyik korábban finanszírozta a Cold War fejlesztését. (Finanszírozta ? He ? Véletlenül nem a 10tacle volt az ? Hiszen ők nem utaltak... - Mr. Water) Mivel ők a jogtulajdonosai a játéknak és ragaszkodtak a megjelenéséhez, ezért megbíztak egy hatfős magyar csapatot a régi Panzers teamből, hogy fejezzék be a hátralévő munkát. Meg is alakult az InnoGlow nevű kis cég, amely az utolsó simításokat végzi el a Cold Waron. (Mese-mese-meskete - Mr. Water)
A játék végül is az Atari kiadásában fog megjelenni a közeljövőben, idehaza a CD Projekt szállítja majd az utolsó Stormregion játékot a tankos programok szerelmeseinek.</p>
</div>
</template>